// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_coefs
SEXP get_coefs(Eigen::Map<Eigen::MatrixXd> X_samp, Eigen::Map<Eigen::VectorXd> Y, Eigen::Map<Eigen::MatrixXd> W);
RcppExport SEXP _mase_get_coefs(SEXP X_sampSEXP, SEXP YSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X_samp(X_sampSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(get_coefs(X_samp, Y, W));
    return rcpp_result_gen;
END_RCPP
}
// get_weights
SEXP get_weights(Eigen::Map<Eigen::MatrixXd> X_pop, Eigen::Map<Eigen::MatrixXd> X_samp, Eigen::Map<Eigen::MatrixXd> W, Eigen::Map<Eigen::MatrixXd> one_mat);
RcppExport SEXP _mase_get_weights(SEXP X_popSEXP, SEXP X_sampSEXP, SEXP WSEXP, SEXP one_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X_pop(X_popSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X_samp(X_sampSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type W(WSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type one_mat(one_matSEXP);
    rcpp_result_gen = Rcpp::wrap(get_weights(X_pop, X_samp, W, one_mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mase_get_coefs", (DL_FUNC) &_mase_get_coefs, 3},
    {"_mase_get_weights", (DL_FUNC) &_mase_get_weights, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_mase(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
