# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_coefs <- function(X_samp, Y, W) {
    .Call(`_mase_get_coefs`, X_samp, Y, W)
}

get_weights <- function(X_pop, X_samp, W, one_mat) {
    .Call(`_mase_get_weights`, X_pop, X_samp, W, one_mat)
}

