# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_weights_greg <- function(X_pop, X_samp, W, one_mat) {
    .Call(`_mase_get_weights_greg`, X_pop, X_samp, W, one_mat)
}

get_weights_modGreg <- function(X_pop_dom, X_samp_dom, W_dom, const1, const2, weighted_indic_mat) {
    .Call(`_mase_get_weights_modGreg`, X_pop_dom, X_samp_dom, W_dom, const1, const2, weighted_indic_mat)
}

const_comp1 <- function(X_samp, W) {
    .Call(`_mase_const_comp1`, X_samp, W)
}

get_coefs <- function(X_samp, Y, W) {
    .Call(`_mase_get_coefs`, X_samp, Y, W)
}

